jobs:
  backend:
    if: startsWith(github.event.comment.body, 'run tests')
    runs-on: ubuntu-latest
    steps:

    - id: extract_pr_number
      run: echo "::set-output name=pr_number::$(echo ${{ github.event.comment.html_url }} | awk -F'#' '{print $(NF-1)}' | awk -F'/' '{print $(NF-0)}')"

    - id: checkout
      uses: actions/checkout@v3
      with:
        ref: "refs/pull/${{ steps.extract_pr_number.outputs.pr_number }}/head"

    - id: echoStep
      run: |
            echo "Inside group"
            echo $(pwd)
            cat $(pwd)/testfile.json



name: "Run tests on Comment"

on:
  issue_comment:
    types: [created, edited]
